### ISSUE TITLE
Deposit posting

### ISSUE THREAD

**Issue by harunurkst** [harunurkst/qard-al-hasana#4]
On click the action button "সঞ্চয় জমা", open a modal to submit deposit.
Modal Header:
নামঃ মোঃ আব্দুর রহমান
সদস্য নংঃ ২
সঞ্চয় স্থিতিঃ ১৫০০ টাকা
form fields:
 - Amount 
 - date (date picker)
 - submit button text should be "সঞ্চয় জমা দিন"
after clicking submit button, show a success message "সঞ্চয় জমা হয়েছে, মোঃ আব্দুল্লাহ, মোট সঞ্চয় ৫৫০ টাকা"

**Comment by Siddiqui-2583** [comment]
started working on this

**Comment by harunurkst** [comment]
can't submit form. please fix this @Siddiqui-2583

**Comment by harunurkst** [comment]
@Siddiqui-2583 
showing success message though API returned 500 error response

**Comment by Waislam** [comment]
showing success message though API returned 500 error response this issue resolved...

**Comment by Waislam** [comment]
Everything is done in this issue

**Comment by harunurkst** [comment]
Showing error message though API returning 201
