### ISSUE TITLE
API documentation with Swagger

### ISSUE THREAD

**Issue by harunurkst** [harunurkst/qard-al-hasana#40]
Create proper API documentation with [Swagger](https://swagger.io/tools/swagger-ui/)

**Comment by rakibul-islam-raju** [comment]
We already have the API documentation implemented. You can access it by visiting the following URLs: -
- Swagger - baseURL
- Redoc - baseURL/redoc/

@harunurkst

**Comment by harunurkst** [comment]
got it, thanks.
