### ISSUE TITLE
Loan disbursement

### ISSUE THREAD

**Issue by harunurkst** [harunurkst/qard-al-hasana#5]
On click the action button "কর্জ প্রদান", open a modal to submit loan disbursement.
modal title/text:  
মোঃ আব্দুল্লাহ
অভিভাবকঃ আবু আব্দুল্লাহ
দলের নামঃ জবা, সদস্য নংঃ ০৫
form fields:
- কর্জের পরিমান
- তারিখ (date picker)
- submit button text should be "কর্জ প্রদান করুন"
after clicking submit button, show a success message "কর্জ প্রদান করা হয়েছে, মোঃ আব্দুল্লাহ, কর্জ ৫০০০ টাকা"

**Comment by Waislam** [comment]
total installment field will be added to the disbursement modal(started working)

**Comment by Waislam** [comment]
Done

**Comment by harunurkst** [comment]
send pull request

**Comment by harunurkst** [comment]
@Waislam 
date field should auto-set todays date

**Comment by Waislam** [comment]
date auto selection is done..

**Comment by harunurkst** [comment]
submit a pull request please

**Comment by Waislam** [comment]
pull request done
