### ISSUE TITLE
Loan Installment

### ISSUE THREAD

**Issue by harunurkst** [harunurkst/qard-al-hasana#6]
On click the action button "কর্জের কিস্তি", open a modal to submit loan disbursement.
modal title/text:
মোঃ আব্দুল্লাহ
কর্জ ৫০০০ টাকা।
কর্জের তারিখঃ ১২-১০-২২
স্থিতিঃ ২০০০ টাকা
form fields:

টাকার পরিমান
তারিখ (date picker)
submit button text should be "কিস্তি জমা দিন"
after clicking submit button, show a success message "কর্জের কিস্তি জমা হয়েছে, মোঃ আব্দুল্লাহ, কর্জ ৫০০০ টাকা, স্থিতিঃ ১৫০০ টাকা"

**Comment by shuvo-me** [comment]
is all text will be in bengali language? @harunurkst @tusheer

**Comment by harunurkst** [comment]
We may use Bengali now, and later we may switch to multi-language.

**Comment by Siddiqui-2583** [comment]
Starting this one. @harunurkst bhaia
